

url: 'https://digital.nhs.uk/data-and-information/publications/statistical/appointments-in-general-practice/january-2023'


nims:
  regex: "Covid Vaccination Appointments"
  filename: "nims"

summary:
  regex: "^Appointments.*Summary$"
  filename: "summary"
